#!/bin/bash

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi



export OPENSSL_LIBS="-L /usr/lib64 -llibeay32 -lssleay32 -llibcrypto -luser32 -lgdi32 -lwsock32 -lws2_32"
CURRENT=`pwd`
export CURRENT
export FFMPEG_FOLDER="3rd_64"

# macos is seen as 'darwin'
if [[ "$OSTYPE" == "darwin"* ]]; then
        cd ../$FFMPEG_FOLDER
else
        SCRIPT=$(realpath -s "$0")
		SCRIPTPATH=$(dirname "$SCRIPT")
		echo "Paths:"
		echo $SCRIPT
		echo $SCRIPTPATH
		cd $SCRIPTPATH
		echo $(pwd)
		cd $FFMPEG_FOLDER || exit
fi

echo "entering $FFMPEG_FOLDER"
chmod u+x build-gcc.sh
. ./build-gcc.sh
cd $CURRENT || exit
