#ifndef H5_STILL_IMAGE_CONFIG_H
#define H5_STILL_IMAGE_CONFIG_H


#include <QtGlobal>

#ifdef BUILD_H5_STILL_IMAGE_LIB
#define H5_STILL_IMAGE_EXPORT Q_DECL_EXPORT
#else
#define H5_STILL_IMAGE_EXPORT Q_DECL_IMPORT
#endif

#endif