name: Build on Linux
on: 

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "releases/**"  ]
  workflow_dispatch:
    inputs:
      compiler:
        required: false
        type: string
        default: gcc
          
  workflow_call:
    inputs:
      compiler:
        required: true
        type: string
        default: gcc

jobs:
    build-linux:
        runs-on: ubuntu-22.04
        
        steps:
        - uses: actions/checkout@v4

        - name: Install Qt
          uses: jurplel/install-qt-action@v4
          
        - name: install gcc 10 
          run: sudo apt update && sudo apt install gcc-10

        - name: Build on Linux
          run: |
              mkdir build 
              cd build 
              cmake .. -DCMAKE_BUILD_TYPE=Debug -DNO_WARNINGS=ON -DWITH_PYTHON=ON -DWITH_FFMPEG=OFF -DLOCAL_INSTALL=ON 
              make -j8 
              cmake --build . --target install
          shell: bash
          env:
           CC:   gcc-10
           CXX:  g++-10

        

