name: Build on MacOS
on: 

  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev", "releases/**"  ]
  workflow_dispatch:
    inputs:
      compiler:
        required: false
        type: string
        default: clang
          
  workflow_call:
    inputs:
      compiler:
        required: true
        type: string
        default: clang

jobs:
    build-macos:
        runs-on: macos-latest
        
        steps:
        - uses: actions/checkout@v4
        
        - name: install qt6 
          run: brew install qt6
          
        - name: install ffmpeg 
          run: brew install ffmpeg
          
        - name: install coreutils
          run: brew install coreutils
          
        #- name: install numpy
        #  run: pip install numpy

        - name: Build on MacOS
          run: |
              mkdir build 
              cd build 
              cmake .. -DCMAKE_BUILD_TYPE=Debug -DWITH_FFMPEG=ON -DWITH_LOCAL_FFMPEG=OFF -DNO_WARNINGS=ON -DLOCAL_INSTALL=ON 
              cmake --build ./ 
              cmake --build . --target install

        
