name: Build on MacOS
on: 

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "releases/**"  ]
  workflow_dispatch:
    inputs:
      compiler:
        required: false
        type: string
        default: clang
          
  workflow_call:
    inputs:
      compiler:
        required: true
        type: string
        default: clang

jobs:
    build-macos:
        runs-on: macos-latest
        
        steps:
        - uses: actions/checkout@v4

        - name: Install Qt
          uses: jurplel/install-qt-action@v4

        - name: Build on MacOS
          run: |
              mkdir build 
              cd build 
              cmake .. -DCMAKE_BUILD_TYPE=Debug -DNO_WARNINGS=ON -DLOCAL_INSTALL=ON 
              cmake --build ./ 
              cmake --build . --target install

        
